# Generated by Django 5.2.4 on 2025-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='screen_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
