# Generated by Django 5.2.4 on 2025-07-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
