# Generated by Django 5.2.4 on 2025-07-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_seat_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
