# Generated by Django 5.2.4 on 2025-07-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_seat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='showtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.showtime'),
        ),
    ]
