# Generated by Django 5.2.4 on 2025-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_seat_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='screen_number',
            field=models.IntegerField(choices=[(1, 'Screen 1'), (2, 'Screen 2'), (3, 'Screen 3')]),
        ),
    ]
