# Generated by Django 5.2.4 on 2025-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Premium', 'Premium'), ('Gold', 'Gold')], default='Gold', max_length=10),
            preserve_default=False,
        ),
    ]
