# Generated by Django 5.2.4 on 2025-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_seat_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
