# Generated by Django 5.2.4 on 2025-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_movie_screen_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
    ]
